import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'yoga shorts',
      slug: 'yoga-short',
      category: 'shorts',
      image: '/images/yogapant.jpg',
      price: 70,
      brand: 'fashion',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'yoga shorts',
      isFeatured: true,
      banner: '/images/yogapant.jpg',
    },
    {
      name: 'sportswear',
      slug: 'slim-fit',
      category: 'men',
      image: '/images/sportswear.jpg',
      price: 80,
      brand: 'Adias',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular gym wear',
      isFeatured: true,
      banner: '/images/sportswear.jpg',
    },
    {
      name: 'yoga pants ',
      slug: 'yoga-pants',
      category: 'ladies',
      image: '/images/yogapants.jpg',
      price: 90,
      brand: 'Logo',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular yoga wear',
      isFeatured: true,
      banner: '/images/yogapants.jpg',
    },
    {
      name:'weight lifting gloves',
      slug: 'gloves',
      category: 'unisex',
      image: '/images/glove.jpg',
      price: 90,
      brand: 'Logo',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking gloves',
      isFeatured: true,
      banner: '/images/glove.jpg',
    },
    {
      name: 'resistance exercise bands',
      slug: 'resistance-bands',
      category: 'unisex',
      image: '/images/latex.jpg',
      price: 95,
      brand: 'yogi',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular gym equipment',
    },
    {
      name: 'yoga pants',
      slug: 'pink-yoga-short',
      category: 'ladies',
      image: '/images/pink.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular yoga wear',
    },
    {
      name: 'vest',
      slug: 'men-vest',
      category: 'men',
      image: '/images/vest.jpg',
      price: 75,
      brand: 'nik',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular vest wear',
    },
    {
      name: '5 peice workout outfits',
      slug: '5-peice',
      category: 'ladies',
      image: '/images/loriso.jpg',
      price: 75,
      brand: 'loriso',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular workout wear',
    },
    {
      name: 'jogger',
      slug: 'men-jogger',
      category: 'men',
      image: '/images/jogger.jpg',
      price: 75,
      brand: 'nik',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular men wear',
    },
    {
      name: 'boxxing gloves',
      slug: 'boxxing-gloves',
      category: 'unisex',
      image: '/images/box.jpg',
      price: 75,
      brand: 'nik',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular boxxing gloves',
    },
    {
      name: '4 kgs dumbell',
      slug: 'dum-bell',
      category: 'unisex',
      image: '/images/dumb.jpg',
      price: 75,
      brand: 'nik',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular dumbell',
    },
    {
      name: 'dumbells',
      slug: 'dumb-ells',
      category: 'unisex',
      image: '/images/dumbe.jpg',
      price: 75,
      brand: 'nik',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular dumbell',
    },
    {
      name: 'portable yoga mat',
      slug: 'yoga-mat',
      category: 'unisex',
      image: '/images/mat.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular yoga mat',
    },
  ],
};

export default data;
